name: demo-07
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow==2.1.1
  - numpy==1.23.5
  - hydra-core=1.0.6
  - pip:
      - wandb==0.10.31
      - protobuf==3.20.1